steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  id: 'npm-install'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']
  waitFor: ['npm-install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  waitFor: ['npm-install']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull us.gcr.io/$PROJECT_ID/ef-discord-bot:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'us.gcr.io/$PROJECT_ID/ef-discord-bot',
            '-t', '${COMMIT_SHA}',
            '--cache-from', 'us.gcr.io/$PROJECT_ID/ef-discord-bot:latest',
            '.'
        ]
images:
- 'us.gcr.io/$PROJECT_ID/ef-discord-bot:latest'
