steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/ef-discord-bot:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/ef-discord-bot',
            '--cache-from', 'gcr.io/$PROJECT_ID/ef-discord-bot:latest'
            '.'
        ]
images:
- 'gcr.io/$PROJECT_ID/ef-discord-bot:latest'
